name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.9-dev
          - 3.10-dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        id: deps_cache
        with:
          path: |
            ${{ env.pythonLocation}}/lib/*/site-packages/*
            ${{ env.pythonLocation}}/bin/*
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Cache cache files
        uses: actions/cache@v2
        with:
          path: "src/*.cache"
          key: ${{ runner.os }}-src-cache-${{ matrix.python-version }}-${{ hashFiles('src/*.cache') }}
          restore-keys: |
            ${{ runner.os }}-src-cache-${{ matrix.python-version }}-${{ hashFiles('src/*.cache') }}
            ${{ runner.os }}-src-cache-${{ matrix.python-version }}-
            ${{ runner.os }}-src-cache-
            ${{ runner.os }}-src-
            ${{ runner.os }}-
      - name: setup-ci
        run: make setup-ci
      - name: lint
        run: make lint
      - name: run
        run: make run
      - name: Upload generated artifacts for the sake of ... fun!
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ matrix.python-version }}
          path: |
            src/*.cache
            *.pack
            *.png
            *.wav
        if: ${{ always() }}
